name: Storefront 1000030519
on: [push]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy to Oxygen
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli

      - name: Login to Shopify
        run: shopify login --store=${{ secrets.SHOPIFY_STORE_URL }} --password=${{ secrets.SHOPIFY_API_TOKEN }}
        
      - name: Deploy to Oxygen
        run: shopify hydrogen deploy --path=./dist
